# -------------------------------------------------------------------------------------------------
# Default Options
# -------------------------------------------------------------------------------------------------

# How big should the player's vault selection menu be by default?
# This only takes affect if they aren't given the appropriate permission nodes
Default Vault Selection Menu Size: 6

# How big should the user's vault be by default
# This only takes affect if they aren't given the appropriate permission nodes
Default Vault Size: 6

# How many vaults should the user be allowed to access by default?
# This only takes affect if they aren't given the appropriate permission nodes
Default Max Allowed Vaults: 3

# Save to file after every vault close, this could possibly get laggy... or result in some fun console errors
Save To File After Every Vault Close: false

# Only save vaults with changes to the file. If false, CosmicVaults will save every single vault during the auto save
# and plugin disable/reload regardless if that particular vault was edited / changed.
Only Save Vaults With Changes: true

Default Vault Title: "&7Vault #&d{vault_number}"
Default Vault Desc: "&7Default description"

# Blocked materials
Blocked Materials:
  - ENDER_CHEST

# if true, it will ignore the Vault Icons section
# and automatically grab any valid inventory material
Use Available Materials: true

# Materials that can be used as a vault icon
Vault Icons:
  - LEATHER_HELMET
  - IRON_HELMET
  - GOLD_HELMET
  - DIAMOND_HELMET
  - LEATHER_CHESTPLATE
  - IRON_CHESTPLATE
  - GOLD_CHESTPLATE
  - DIAMOND_CHESTPLATE
  - LEATHER_LEGGINGS
  - IRON_LEGGINGS
  - GOLD_LEGGINGS
  - DIAMOND_LEGGINGS
  - LEATHER_BOOTS
  - IRON_BOOTS
  - GOLD_BOOTS
  - DIAMOND_BOOTS
  - IRON_SWORD
  - GOLD_SWORD
  - DIAMOND_SWORD
  - IRON_PICKAXE
  - GOLD_PICKAXE
  - DIAMOND_PICKAXE
  - BOW
  - ARROW
  - APPLE
  - BAKED_POTATO
  - BREAD
  - CAKE
  - CHICKEN
  - BEEF
  - PORKCHOP
  - RABBIT
  - COOKIE
  - BLAZE_ROD
  - MOB_SPAWNER
  - SPIDER_EYE
  - SPONGE
  - SAND
  - GRASS
  - GLASS
  - GOLD_INGOT
  - DIAMOND
  - IRON_INGOT
  - PAPER
  - BOOK
  - REDSTONE
  - REDSTONE_BLOCK
  - REPEATER
  - COMPARATOR
  - SADDLE
  - SHEARS
  - SLIME_BALL
  - SUGAR
  - SUGAR_CANE
  - TNT
  - WHEAT
  - WHEAT_SEEDS
  - TORCH
  - REDSTONE_TORCH
  - SLIME_BLOCK
  - QUARTZ
  - QUARTZ_BLOCK
  - RABBIT_FOOT
  - PUFFERFISH
  - PRISMARINE
  - PRISMARINE_CRYSTALS
  - CACTUS
  - POPPY
  - PACKED_ICE
  - MAP
  - MILK_BUCKET


# Settings regarding auto save, it's recommend to use this option over the `Save To File After Every Vault Close` one
Auto Save:
  Enabled: true
  Save Delay: 30 minutes

# -------------------------------------------------------------------------------------------------
# GUI Formatting Options
# -------------------------------------------------------------------------------------------------
Guis:
  Player Selection:
    Title: "&dSelect Player"
    Items:
      Player:
        Name: "&d{player_name}"
        Lore:
          - "&7Click to view vaults that"
          - "&7this player owns"
  Vault Icon Select:
    Title: "&dSelect Vault Icon"
  Vault Edit:
    Title: "&dEditing Vault #{vault_number}"
    Background Item: BLACK_STAINED_GLASS_PANE
    Rows: 4
    Items:
      Name:
        Slots: [ 11 ]
        Material: NAME_TAG
        Name: "&dVault Name"
        Lore:
          - "&7Current Name&f: {vault_title}"
          - "&7Click to change name"
      Description:
        Slots: [ 13 ]
        Material: WRITABLE_BOOK
        Name: "&dVault Description"
        Lore:
          - "&7Current Description&f: {vault_description}"
          - "&7Click to change description"
      Icon:
        Slots: [ 15 ]
        Name: "&dVault Icon"
        Lore:
          - "&7Click to change icon"
      Reset:
        Slots: [ 21 ]
        Material: END_PORTAL_FRAME
        Name: "&dReset Vault"
        Lore:
          - "&7Click to reset your vault back to"
          - "&7default settings, this does not affect contents"
      Delete:
        Slots: [ 23 ]
        Material: BARRIER
        Name: "&dDelete Vault"
        Lore:
          - "&7Press Drop Key to delete your vault"
          - "&cThis cannot be undone!"
  Vault Selection:
    Title: "&dCosmic Vaults &f-&7 Select Vault"
    Items:
      Locked:
        Material: RED_STAINED_GLASS_PANE
        Name: "&c&lVault Locked"
        Lore:
          - "&7You do not have permission to access this vault"
      Opened:
        # This will be ignored whenever the player changes it
        Material: EMERALD
        Name: "{vault_title}"
        Lore:
          - "{vault_description}"
          - "&7Created&f: &d{vault_creation_date}"
          - "&7Items&f: &d{vault_item_count}"
          - ""
          - "&7Left-Click to open vault"
          - "&7Right-Click to edit vault"
      Unopened:
        Material: LIME_STAINED_GLASS_PANE
        Name: "&a&lUnopened Vault"
        Lore:
          - "&7Click to open this vault"

# -------------------------------------------------------------------------------------------------
# The format used in the {timestamp} placeholder (google "Java timestamp format" for options).
# -------------------------------------------------------------------------------------------------
Timestamp_Format: "MMM/dd/yyyy HH:mm:ss aa"

# -------------------------------------------------------------------------------------------------
# * THE FIRST ALIAS IS THE MAIN LABEL, PLEASE DO NOT REMOVE IT. *
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ cosmicvaults, pv, playervaults ]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied
# to your messages/ folder where you can edit it.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&dCosmicVaults&8]"

# -------------------------------------------------------------------------------------------------
# We log a console message if an operation takes over the time below (milliseconds).
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 1