blank_issues_enabled: false
contact_links:
  - name: Tweetzy Discord
    url: https://discord.tweetzy.ca/
    about: Join the Tweetzy discord server to receive help and be alerted about special offers.